# Generated by Django 4.2.7 on 2026-01-02 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('volume_24h', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('price_change_1h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_change_7d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('volume_change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('rank', models.IntegerField(default=0)),
                ('rank_score', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ارز دیجیتال',
                'verbose_name_plural': 'ارزهای دیجیتال',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('next_update', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'وضعیت پایش',
                'verbose_name_plural': 'وضعیت پایش',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='', max_length=200)),
                ('top_coins_count', models.IntegerField(default=100)),
                ('price_weight', models.DecimalField(decimal_places=2, default=0.4, max_digits=5)),
                ('volume_weight', models.DecimalField(decimal_places=2, default=0.3, max_digits=5)),
                ('stability_weight', models.DecimalField(decimal_places=2, default=0.2, max_digits=5)),
                ('market_cap_weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('data_history_days', models.IntegerField(default=7)),
                ('update_interval', models.IntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('price_change_1h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_change_7d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('volume_change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='models.cryptocurrency')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت',
                'verbose_name_plural': 'تاریخچه قیمت\u200cها',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cryptocurrency', '-timestamp'], name='models_pric_cryptoc_6034c8_idx')],
            },
        ),
    ]
