# Generated by Django 4.2.7 on 2026-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_cryptocurrency_standing_settings_social_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['-rank_score'], 'verbose_name': 'ارز دیجیتال', 'verbose_name_plural': 'ارزهای دیجیتال'},
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='blockchain_site',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='fully_diluted_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='github_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='high_24h',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='homepage_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='low_24h',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='official_forum_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='subreddit_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='total_value_locked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
