# Generated by Django 4.2.7 on 2026-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_add_detailed_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAPICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(db_index=True, max_length=500, unique=True)),
                ('last_successful_request', models.DateTimeField(blank=True, null=True)),
                ('cached_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache API سوشال',
                'verbose_name_plural': 'Cache API\u200cهای سوشال',
                'indexes': [models.Index(fields=['api_url', '-last_successful_request'], name='models_soci_api_url_0a4af8_idx')],
            },
        ),
    ]
